#================================ Inputs =====================================
filebeat.inputs:
###Monitor ssh connection to server through secure log
- type: log
  paths:
  - /var/log/secure
  encoding: utf-8
  fields:
    custom_services: linux-access
  ignore_older: 24h
  processors:
  - drop_fields:
        fields: ["log", "ecs", "agent", "offset", "input"]
  fields_under_root: true
###Monitor yum.log on server
- type: log
  paths:
  - /var/log/yum.log
  encoding: utf-8
  fields:
    custom_services: linux-yum-install
  ignore_older: 24h
  processors:
  - drop_fields:
      fields: ["log", "ecs", "agent", "offset", "input"]
  fields_under_root: true
###Monitor boot.log on server
- type: log
  paths:
  - /var/log/boot.log
  encoding: utf-8
  fields:
    custom_services: linux-boot
  ignore_older: 24h
  processors:
  - drop_fields:
      fields: ["log", "ecs", "agent", "offset", "input"]
  fields_under_root: true
###Monitor fail2ban service
- type: log
  paths:
  - /var/log/fail2ban.log
  encoding: utf-8
  fields:
    custom_services: linux-fail2ban-service
  ignore_older: 24h
  processors:
  - drop_fields:
      fields: ["log", "ecs", "agent", "offset", "input"]
  fields_under_root: true
#Advance config
close_inactive: 3m
close_removed: true
scan_frequency: 30s

#================================ Outputs =====================================
output.logstash:
  hosts: ["10.200.9.51:5514"]
  bulk_max_size: 1024 
max_process: 1
queue.mem:
  events: 256
  flush.min_events: 128
  flush.timeout: 5s
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 30s